### ISSUE TITLE
Update global reports automatically at fixed time(s)

### ISSUE THREAD

**Issue by EwoutH** [cov-lineages/lineages-website-old#5]
It looks like updating the new variant reports (`global_report.md`, `global_report_B.1.1.7.html` and `global_report_B.1.351.html`) is currently done manually. Automating this could improve consistency and reduce manual labour. The pages could be updated daily at a fixed time, or even multiple times a day (depending on how frequently the source data is updated).

I have a bit of CI experience, so I could help on that side, but no idea how the `global_report` files are currently generated. Are there any scripts used? (I assume [grinch](https://github.com/cov-lineages/grinch) is doing the bulk of the work)

**Comment by aineniamh** [comment]
All the html files and images are being generated automatically through grinch using mako, which is a python based templating language. Grinch does have a few scripts in it. I'm currently running manually as there are so many changes each day at unpredictable times, but will probably schedule a cron job when it stabilizes. Thanks for the offer though!

**Comment by EwoutH** [comment]
Thanks for the quick reply! Would it be possible to leave this issue open until a cron job is implemented?

I had started on writing a CI job using GitHub Actions, you can find it over at https://github.com/cov-lineages/grinch/pull/1. Feel free to use the code anyway you like if it's any useful!

**Comment by aineniamh** [comment]
Sure!
